### ISSUE TITLE
Doesn't work ;-)

### ISSUE THREAD

**Issue by wmertens** [proger/python2nix#2]
This is sadly missing from nixpkgs so I cloned the repo and then tried to execute it from a nix-shell with `nix-shell -p pythonPackages.pip -p pythonPackages.requests -p python -p setuptools`. I had to change the `from pip._vendor import pkg_resources` to `import pkg_resources` so it would find the one from setuptools, and then it just doesn't work.

The error is:

    package_to_info failed: <Response [404]>
    Traceback (most recent call last):
      File "./python2nix.py", line 104, in <module>
        print info_to_expr(package_to_info(sys.argv[1]))
      File "./python2nix.py", line 76, in package_to_info
        raise e
    ValueError: No JSON object could be decoded

Thoughts?

**Comment by proger** [comment]
So since horizon isn't really available with pip I'm closing this unless you guys have a suggestion of ways to implement this.

**Comment by wmertens** [comment]
@proger @iElectric  more specifically, I was running python2nix.py against https://github.com/openstack/horizon/blob/master/requirements.txt , sorry for missing this discussion.

**Comment by proger** [comment]
i didn't really think about the case of running against requirements.txt but i guess you can just parse the package names out and get it done easier

unless you have the time and desire to implement automatic dependency chasing :)

**Comment by wmertens** [comment]
well, not at the moment :)
