### ISSUE TITLE
Use sha256 over md5

### ISSUE THREAD

**Issue by domenkozar** [proger/python2nix#5]
md5 is deprecated, let's use sha256 hash for source files :)

**Comment by proger** [comment]
Deprecated by what? nixpkgs?

**Comment by iElectric** [comment]
See https://github.com/NixOS/nixpkgs/issues/4491

**Comment by proger** [comment]
Thanks

**Comment by proger** [comment]
Currently we're using pip's package metadata to get the md5 for the tarball and looks like this change involves either bumping the pip version we use (it's still 1.5.6) or computing the hash manually and using smth like `nix-prefetch-url`. 

Putting this comment to let people stopping by know that's not a super quick win right now.

**Comment by c0bw3b** [comment]
@domenkozar I think we can close this now?
Only md5 left in the tree is inside `libreoffice` and it's only used to compose a name or a URL.
